In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("shu17dist.csv",delimiter = "\t", encoding ="utf-16")

## http://politicalscience.unt.edu/~maeda/

In [3]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

In [4]:
def get_pref(prefid):
    get_pref = df[df["prefid"] == prefid] 
    return get_pref

In [5]:
pref = get_pref(13)

In [6]:
pref

,id,name,prefid,pref,distnum,party,dual,win,inc,votes,tvotes,vshare,age,rank,terms,last_kana,first_kana,rec1,rec3,rec4,rec5,rec39,rec40,rec41,rec42
255,256,海江田万里,13,Tokyo,1,40,1,2,0,96255,236548,40.69,68,1,6,かいえだ,ばんり,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,257,山田美樹,13,Tokyo,1,1,1,1,1,93234,236548,39.41,43,2,2,やまだ,みき,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
257,258,松沢香,13,Tokyo,1,39,1,0,0,40376,236548,17.07,39,3,0,まつざわ,かおる,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,原口実季,13,Tokyo,1,98,0,0,0,3806,236548,1.61,28,4,0,はらぐち,みき,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,犬丸光加,13,Tokyo,1,98,0,0,0,1570,236548,0.66,57,5,0,いぬまる,みつか,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,又吉光雄,13,Tokyo,1,98,0,0,0,1307,236548,0.55,73,6,0,またよし,みつお,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,262,辻清人,13,Tokyo,2,1,1,2,1,112993,246178,45.90,38,1,2,つじ,きよと,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
262,263,松尾明弘,13,Tokyo,2,40,1,0,0,91230,246178,37.06,42,2,0,まつお,あきひろ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,264,鳩山太郎,13,Tokyo,2,39,1,0,0,41955,246178,17.04,43,3,0,はとやま,たろう,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,265,石原宏高,13,Tokyo,3,1,1,2,1,107708,247176,43.58,53,1,3,いしはら,ひろたか,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
265,266,松原仁,13,Tokyo,3,39,1,1,1,94380,247176,38.18,61,2,6,まつばら,じん,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,267,香西克介,13,Tokyo,3,4,0,0,0,45088,247176,18.24,41,3,0,こうざい,かつすけ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,268,平将明,13,Tokyo,4,1,1,2,1,115239,230108,50.08,50,1,4,たいら,まさあき,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
268,269,井戸正枝,13,Tokyo,4,40,1,0,0,53480,230108,23.24,51,2,1,いど,まさえ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,270,難波美智代,13,Tokyo,4,39,1,0,0,35352,230108,15.36,43,3,0,なんば,みちよ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,271,青山昂平,13,Tokyo,4,4,0,0,0,26037,230108,11.32,26,4,0,あおやま,こうへい,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,272,若宮健嗣,13,Tokyo,5,1,1,2,1,101314,246233,41.15,56,1,3,わかみや,けんじ,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
272,273,手塚仁雄,13,Tokyo,5,40,1,1,0,99182,246233,40.28,51,2,3,てづか,よしお,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,274,福田峰之,13,Tokyo,5,39,1,0,1,45737,246233,18.57,53,3,3,ふくだ,みねゆき,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,275,落合貴之,13,Tokyo,6,40,1,2,1,100400,245991,40.81,38,1,1,おちあい,たかゆき,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,276,越智隆雄,13,Tokyo,6,1,1,1,1,98422,245991,40.01,53,2,3,おち,たかお,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
276,277,植松恵美子,13,Tokyo,6,39,1,0,0,42862,245991,17.42,49,3,0,うえまつ,えみこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,278,中岡茉妃,13,Tokyo,6,98,0,0,0,4307,245991,1.75,26,4,0,なかおか,まき,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,279,長妻昭,13,Tokyo,7,40,1,2,1,117118,231804,50.52,57,1,6,ながつま,あきら,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,280,松本文明,13,Tokyo,7,1,1,1,1,85305,231804,36.80,68,2,3,まつもと,ふみあき,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
280,281,荒木章博,13,Tokyo,7,39,1,0,0,25531,231804,11.01,64,3,0,あらき,あきひろ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
281,282,井上郁磨,13,Tokyo,7,99,0,0,0,3850,231804,1.66,26,4,0,いのうえ,いくま,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,283,石原伸晃,13,Tokyo,8,1,1,2,1,99863,254648,39.22,60,1,9,いしはら,のぶてる,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
283,284,吉田晴美,13,Tokyo,8,40,1,0,0,76283,254648,29.96,45,2,0,よしだ,はるみ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,285,木内孝胤,13,Tokyo,8,39,1,0,1,41175,254648,16.17,51,3,2,きうち,たかたね,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,286,長内史子,13,Tokyo,8,4,0,0,0,22399,254648,8.80,29,4,0,おさない,ふみこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,287,円より子,13,Tokyo,8,99,0,0,0,11997,254648,4.71,70,5,0,まどか,よりこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,288,斎藤郁真,13,Tokyo,8,98,0,0,0,2931,254648,1.15,29,6,0,さいとう,いくま,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,289,菅原一秀,13,Tokyo,9,1,1,2,1,122279,248692,49.17,55,1,5,すがわら,いっしゅう,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
289,290,高松智之,13,Tokyo,9,39,1,0,0,64731,248692,26.03,43,2,0,たかまつ,さとし,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,291,原純子,13,Tokyo,9,4,1,0,0,57439,248692,23.10,53,3,0,はら,じゅんこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,292,前田吉成,13,Tokyo,9,99,0,0,0,4243,248692,1.71,62,4,0,まえだ,よしなり,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,293,鈴木隼人,13,Tokyo,10,1,1,2,1,91146,243894,37.37,40,1,1,すずき,はやと,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
293,294,鈴木庸介,13,Tokyo,10,40,1,0,0,70168,243894,28.77,41,2,0,すずき,ようすけ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,295,若狭勝,13,Tokyo,10,39,1,0,1,57901,243894,23.74,60,3,2,わかさ,まさる,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,296,岸良信,13,Tokyo,10,4,0,0,0,20828,243894,8.54,62,4,0,きし,よしのぶ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,297,小山徹,13,Tokyo,10,99,0,0,0,2107,243894,0.86,42,5,0,こやま,とおる,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,298,吉井利光,13,Tokyo,10,98,0,0,0,1744,243894,0.72,35,6,0,よしい,としみつ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,299,下村博文,13,Tokyo,11,1,1,2,1,104612,232997,44.90,63,1,7,しもむら,はくぶん,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
299,300,前田順一郎,13,Tokyo,11,40,1,0,0,60291,232997,25.88,42,2,0,まえだ,じゅんいちろう,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,301,宍戸千絵,13,Tokyo,11,39,1,0,0,42668,232997,18.31,39,3,0,ししど,ちえ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,302,小堤東,13,Tokyo,11,4,0,0,0,25426,232997,10.91,28,4,0,こづつみ,あずま,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,303,太田昭宏,13,Tokyo,12,3,0,2,1,112597,218033,51.64,72,1,7,おおた,あきひろ,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,304,池内沙織,13,Tokyo,12,4,1,0,1,83544,218033,38.32,35,2,1,いけうち,さおり,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,305,中村勝,13,Tokyo,12,98,0,0,0,21892,218033,10.04,66,3,0,なかむら,まさる,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,306,鴨下一郎,13,Tokyo,13,1,1,2,1,120744,218621,55.23,68,1,8,かもした,いちろう,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
306,307,北條智彦,13,Tokyo,13,40,1,0,0,67070,218621,30.68,34,2,0,きたじょう,ともひこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,308,祖父江元希,13,Tokyo,13,4,0,0,0,30807,218621,14.09,42,3,0,そぶえ,もとき,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,309,松島みどり,13,Tokyo,14,1,1,2,1,104137,221861,46.94,61,1,5,まつしま,みどり,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
309,310,矢作麻子,13,Tokyo,14,39,1,0,0,63235,221861,28.50,39,2,0,やはぎ,あさこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,311,阿藤和之,13,Tokyo,14,4,0,0,0,46600,221861,21.00,46,3,0,あとう,かずゆき,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,312,清井美穂,13,Tokyo,14,98,0,0,0,4282,221861,1.93,54,4,0,せいい,みほ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,313,大塚紀久雄,13,Tokyo,14,99,0,0,0,3607,221861,1.63,76,5,0,おおつか,きくお,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,314,秋元司,13,Tokyo,15,1,1,2,1,101155,222090,45.55,46,1,2,あきもと,つかさ,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
314,315,柿沢未途,13,Tokyo,15,39,1,1,1,70325,222090,31.67,46,2,3,かきざわ,みと,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,316,吉田年男,13,Tokyo,15,4,0,0,0,34943,222090,15.73,69,3,0,よしだ,としお,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,317,猪野隆,13,Tokyo,15,99,0,0,0,15667,222090,7.05,52,4,0,いの,たかし,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,318,大西英男,13,Tokyo,16,1,1,2,1,84457,206430,40.91,71,1,2,おおにし,ひでお,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
318,319,初鹿明博,13,Tokyo,16,40,1,1,1,71405,206430,34.59,48,2,2,はつしか,あきひろ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,320,田村謙治,13,Tokyo,16,39,1,0,0,50568,206430,24.50,49,3,3,たむら,けんじ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,321,平沢勝栄,13,Tokyo,17,1,1,2,1,127632,220255,57.95,72,1,7,ひらさわ,かつえい,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,322,西田主税,13,Tokyo,17,39,1,0,0,49485,220255,22.47,55,2,0,にしだ,ちから,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,323,新井杉生,13,Tokyo,17,4,0,0,0,43138,220255,19.59,58,3,0,あらい,すぎお,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,324,菅直人,13,Tokyo,18,40,1,2,1,96713,237461,40.73,71,1,12,かん,なおと,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,325,土屋正忠,13,Tokyo,18,1,0,0,1,95667,237461,40.29,75,2,3,つちや,まさただ,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
325,326,鴇田敦,13,Tokyo,18,39,1,0,0,45081,237461,18.98,51,3,0,ときた,あつし,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,327,松本洋平,13,Tokyo,19,1,1,2,1,96229,233889,41.14,44,1,3,まつもと,ようへい,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
327,328,末松義規,13,Tokyo,19,40,1,1,0,90540,233889,38.71,60,2,5,すえまつ,よしのり,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,329,佐々木里加,13,Tokyo,19,39,1,0,0,29743,233889,12.72,50,3,0,ささき,りか,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,330,杉下茂雄,13,Tokyo,19,4,0,0,0,17377,233889,7.43,68,4,0,すぎした,しげお,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,331,木原誠二,13,Tokyo,20,1,1,2,1,107686,215866,49.89,47,1,3,きはら,せいじ,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
331,332,宮本徹,13,Tokyo,20,4,1,1,1,57741,215866,26.75,45,2,1,みやもと,とおる,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,333,鹿野晃,13,Tokyo,20,39,1,0,0,50439,215866,23.37,44,3,0,かの,あきら,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,334,長島昭久,13,Tokyo,21,39,1,2,1,92356,225431,40.97,55,1,5,ながしま,あきひさ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,335,小田原潔,13,Tokyo,21,1,1,1,1,88225,225431,39.14,53,2,2,おだわら,きよし,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
335,336,小糸健介,13,Tokyo,21,5,1,0,0,38195,225431,16.94,35,3,0,こいと,けんすけ,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
336,337,天木直人,13,Tokyo,21,98,0,0,0,6655,225431,2.95,70,4,0,あまき,なおと,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,338,伊藤達也,13,Tokyo,22,1,1,2,1,110493,254661,43.39,56,1,7,いとう,たつや,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
338,339,山花郁夫,13,Tokyo,22,40,1,1,0,91073,254661,35.76,50,2,3,やまはな,いくお,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,340,金ケ崎絵美,13,Tokyo,22,39,1,0,0,30236,254661,11.87,41,3,0,かながさき,えみ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,341,阿部真,13,Tokyo,22,4,0,0,0,22859,254661,8.98,43,4,0,あべ,まこと,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,342,小倉将信,13,Tokyo,23,1,1,2,1,110522,245901,44.95,36,1,2,おぐら,まさのぶ,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
342,343,伊藤俊輔,13,Tokyo,23,39,1,1,0,76450,245901,31.09,38,2,0,いとう,しゅんすけ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,344,松村亮佑,13,Tokyo,23,4,0,0,0,58929,245901,23.96,37,3,0,まつむら,りょうすけ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,345,萩生田光一,13,Tokyo,24,1,1,2,1,122331,248013,49.32,54,1,4,はぎうだ,こういち,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
345,346,高橋斉久,13,Tokyo,24,40,1,0,0,61441,248013,24.77,44,2,0,たかはし,なりひさ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,347,吉羽美華,13,Tokyo,24,39,1,0,0,39892,248013,16.08,37,3,0,よしば,みか,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,348,飯田美弥子,13,Tokyo,24,4,1,0,0,24349,248013,9.82,57,4,0,いいだ,みやこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,349,井上信治,13,Tokyo,25,1,1,2,1,112014,216215,51.81,48,1,5,いのうえ,しんじ,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
349,350,山下容子,13,Tokyo,25,40,1,0,0,44884,216215,20.76,58,2,0,やました,ようこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,351,小沢鋭仁,13,Tokyo,25,39,1,0,1,38286,216215,17.71,63,3,8,おざわ,さきひと,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,352,井上宣,13,Tokyo,25,4,0,0,0,21031,216215,9.73,43,4,0,いのうえ,たかし,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
pref.iat[0,3]
#prefから県名を取り出す

'Tokyo'

In [86]:
#からのデータフレーム作るよ
cols = ["1","3","4","5","39","40","41","98","99","100","101","102","103","104"]
void = np.random.rand(3,4)

In [87]:
totalvotes = pref[pref["win"] == 2]
totalvotes = sum(totalvotes["tvotes"])
totalvotes

5848996

### 党派にて分けるには？？？？
> 自民公明は多くお場合どちらかが小選挙区に立候補している場合もう片方の推薦がある

> 野党共闘は2017年の時点でどこまで進んでいたのか？

政党別に分けているものを別の区切りで分けよう

## 与野党勢力ごとに考える
言い換えればどうやって勢力を分けるか考える

> 自公連立
>> 1. 小選挙区の政党別立候補<-party1 or party3
1. 推薦、つまりrec1 or rec3であること
    1. 無所属で自民公明から推薦を受けている候補者も自公連立に含める

> 野党勢力
>> 1. ~~まとめるの無理じゃね？~~
1. 条件として、立憲民主党、共産党、社民党、自由党が同じ選挙区内で競合していない場合は共闘しているということ   一つのまとまりとみなす
        1. (rec4 or rec5 or rec40 or rec 42) | 
1. 維新、希望は~~それぞれ一つの勢力~~同一選挙区内に両党が同時に候補者を擁立していない限り同一
1. その他政党、無所属は単独のものとみなす


prefの中身をこれに従って書き換える?<- distごとに
> prefのrowの党という属性を書き換える
1. prefをdistnumで分割する
    1. distnumごとに読み込む(繰り返し)
            while distnum <= int(distnums):
                dist = pref[pref["distnum"] == distnum]
       1. 各distごとに野党共闘の有無を確認する<-if文?　
       1. 各選挙区における候補者の所属政党を属性として判断<- party4,5,40の属性を持つ候補者が二人いればそれを例外処理
       1. ~~それを調べるためのコードってどう書くんだ???~~

### 上で書いた課題を解決したい
条件を考えよう

1. distごとにparty4,5,40のrowを取り出して、そのcolumn数>1なら除外でよくね
        
        opposition_party1 = dist[dist["party"] == 4 | 5 | 40]
        if len(opposition_party1.columns) > 1:
            どうしよう(pass?<-まさか)
        else: 
            dist.loc[dist["party"] == 4 | 5 | 40, "party"] = "Y" <-的な？
            
> elseでいいのか？？？

1. 希望の党とかはparty39,41で同じ操作をする

        opposition_party2 = dist[dist["party"] == 39 | 41]
        if len(opposition_party2.columns) > 1:
            どうしよう
        else:
            dist.loc[dist["party"] == 39 | 41, "party"] = "Z"
            
            
谜
1. elif使って一気に分岐をさせたいけどどうなるんだろ
2. ~~どうしようを何とかする~~

### 自公連立を考える
上記の1,2の条件を満たすだけでよくね？
        
    if (dist["party"] == 1 | 3) or (dist["rec1"] == True | dist["rec3"] == True):
        dist.loc[dist["party"] == 1 | 3, "party"] = "X"
        dist.loc[dist["rec1"] | ["rec3"]] = "X"
        
知らん

## なぜ茨城でばぐったか
公明党の推薦と自民党の候補が異なるから、一つの選挙区内にX党が2人立候補してることになってしまう

### 対処
野党共闘除外のコードの流用

In [88]:
#から！
void = np.random.rand(3,4)

distnums = pref["distnum"][-1:]

void = np.random.rand(int(distnums),17)
void = pd.DataFrame(void)
void.columns = ["1","3","4","5","39","40","41","98","99","100","101","102","103","104","X","Y","Z"]
void = void[void[:] ==0]

distnum = 1

while distnum <= int(distnums):
    dist = pref[pref["distnum"] == distnum]
        #選挙区別に分けた
        
    if any(dist["party"] == 1) == 1 or any(dist["party"] == 1) == 1:
        gp1 = dist[(dist["party"] == 1) | (dist["party"] == 3) | (dist["rec1"] == 1) | (dist["rec3"] == 1)]
        if len(gp1) > 1:
            pass
        else:
            dist.loc[dist["party"] == 1, "party"] = "X"
            dist.loc[dist["party"] == 3,"party"] = "X"
    
    if any(dist["party"] == 4) == 1 or any(dist["party"] == 5) or any(dist["party"] == 40) == 1:
        oplist1=[4,5,40]
        opposition_party1 = dist[(dist["party"] == 4) | (dist["party"] == 5) | (dist["party"] == 40)]
        #print(opposition_party1)
        
        if len(opposition_party1) > 1:
            pass
        
        else:
            for op1 in oplist1:
                dist.loc[dist["party"] == op1, "party"] = "Y"
        
    if any(dist["party"] == 39) == 1 or any(dist["party"] == 41) == 1:
        oplist2=[39,41]
        opposition_party2 = dist[(dist["party"] == 39) | (dist["party"] == 41)]
        #print(opposition_party2)
        
        if len(opposition_party2) > 1:
            pass
        
        else:
            for op2 in oplist2:
                dist.loc[dist["party"] == op2, "party"] = "Z"
        
        #print(dist)

    if any(dist["rec1"] == 1) == 1 or any(dist["rec3"] == 1) == 1:
        gp1 = dist[(dist["party"] == 1) | (dist["party"] == 3) | (dist["rec1"] == 1) | (dist["rec3"] == 1)]
        
        if len(gp1) > 1:
            pass
        else:
            dist.loc[dist["rec1"] == 1,"party"] = "X"
            dist.loc[dist["rec3"] == 1,"party"] = "X"
        
    if any(dist["rec4"] == 1) == 1 or any(dist["rec5"] == 1) or any(dist["rec40"] == 1) or any(dist["rec42"] == 1):
        oplist1rec = ["rec4","rec5","rec40","rec42"]
        opmistery1 = dist[(dist["rec4"] == 1) | (dist["rec5"] == 1) | (dist["rec40"] == 1) | (dist["rec42"] == 1)]
        if len(opmistery1) > 1:
            pass
        else:
            for op1list in oplist1rec:
                dist.loc[dist[op1list] == 1, "party"] = "Y"
        #dist.loc[dist["rec4"] == 1,"party"] = "Y"
            
    if any(dist["rec39"] == 1) == 1 or any(dist["rec41"] == 1) == 1:
        opmistery2 = dist[(dist["party"] == 39) | (dist["party"] == 41) | (dist["rec39"] == 1) | (dist["rec41"] == 1)]
        if len(opmistery2) > 1:
            pass
        else:
            dist.loc[dist["rec39"] == 1,"party"] = "Z"
            dist.loc[dist["rec41"] == 1,"party"] = "Z"
        
        #print(dist)
    
    for party in [1,3,4,5,39,40,41,98,99,"X","Y","Z"]:
        dist_each_party = dist[dist["party"] == party]
        #<-
        
        #row=0でpass
        if len(dist_each_party) ==0:
            pass
        elif len(dist_each_party) >1:
            #print(dist_each_party)
            mul_ca=1
            #print("!!!!!",len(dist_each_party))
            while mul_ca <= len(dist_each_party):
                ex99 = dist_each_party[mul_ca-1:mul_ca]
                #print (ex99)
                if all(ex99["win"] == 2) == 1:
                    wasted = dist["votes"].iat[0] - dist["votes"].iat[1]
                    void[str(mul_ca-1 + party)][distnum-1] = wasted
                    #
                    
                    #try:
                     #   void[str(mul_ca-1 + party)][distnum-1] = wasted
                    ##except unsupported operand type(s) for +: 'int' and 'str':
                      #  void.loc[]
                    
                elif all(ex99["win"] == 2) ==0:
                    wasted=ex99["votes"]
                    void[str(mul_ca + party)][distnum-1]=wasted
                print("dist",distnum,"party仮",mul_ca + party,"wasted",wasted)
                
                mul_ca +=1
                #print ("!!!!!",mul_ca)
                #if mul_ca==len(dist_each_party):
                    #break
                #else:
                    #pass
        
        else:

            if all(dist_each_party["win"] == 2) == 1:
                wasted = dist["votes"].iat[0] - dist["votes"].iat[1]

                void[str(party)][distnum-1] = wasted
            
            elif all(dist_each_party["win"] != 2) == 1:
                wasted=dist_each_party["votes"]
                
      
                void[str(party)][distnum-1] =wasted
                
            else:
                pass
                #wasted = dist["votes"]
            print("dist",distnum,"party",party,"wasted",wasted)
        
    distnum += 1
    #print(dist)
void

dist 1 party仮 99 wasted 258    3806
Name: votes, dtype: int64
dist 1 party仮 100 wasted 259    1570
Name: votes, dtype: int64
dist 1 party仮 101 wasted 260    1307
Name: votes, dtype: int64
dist 1 party X wasted 256    93234
Name: votes, dtype: int64
dist 1 party Y wasted 3021
dist 1 party Z wasted 257    40376
Name: votes, dtype: int64
dist 2 party X wasted 21763
dist 2 party Y wasted 262    91230
Name: votes, dtype: int64
dist 2 party Z wasted 263    41955
Name: votes, dtype: int64
dist 3 party X wasted 13328
dist 3 party Y wasted 266    45088
Name: votes, dtype: int64
dist 3 party Z wasted 265    94380
Name: votes, dtype: int64
dist 4 party 4 wasted 270    26037
Name: votes, dtype: int64
dist 4 party 40 wasted 268    53480
Name: votes, dtype: int64
dist 4 party X wasted 61759
dist 4 party Z wasted 269    35352
Name: votes, dtype: int64
dist 5 party X wasted 2132
dist 5 party Y wasted 272    99182
Name: votes, dtype: int64
dist 5 party Z wasted 273    45737
Name: votes, dtype: int64
dist 6 party 98 wasted 277    4307
Name: votes, dtype: int64
dist 6 party X wasted 275    98422
Name: votes, dtype: int64
dist 6 party Y wasted 1978
dist 6 party Z wasted 276    42862
Name: votes, dtype: int64
dist 7 party 99 wasted 281    3850
Name: votes, dtype: int64
dist 7 party X wasted 279    85305
Name: votes, dtype: int64
dist 7 party Y wasted 31813
dist 7 party Z wasted 280    25531
Name: votes, dtype: int64
dist 8 party 4 wasted 285    22399
Name: votes, dtype: int64
dist 8 party 40 wasted 283    76283
Name: votes, dtype: int64
dist 8 party 98 wasted 287    2931
Name: votes, dtype: int64
dist 8 party 99 wasted 286    11997
Name: votes, dtype: int64
dist 8 party X wasted 23580
dist 8 party Z wasted 284    41175
Name: votes, dtype: int64
dist 9 party 99 wasted 291    4243
Name: votes, dtype: int64
dist 9 party X wasted 57548
dist 9 party Y wasted 290    57439
Name: votes, dtype: int64
dist 9 party Z wasted 289    64731
Name: votes, dtype: int64
dist 10 party 4 wasted 295    20828
Name: votes, dtype: int64
dist 10 party 40 wasted 293    70168
Name: votes, dtype: int64
dist 10 party 98 wasted 297    1744
Name: votes, dtype: int64
dist 10 party 99 wasted 296    2107
Name: votes, dtype: int64
dist 10 party X wasted 20978
dist 10 party Z wasted 294    57901
Name: votes, dtype: int64
dist 11 party 4 wasted 301    25426
Name: votes, dtype: int64
dist 11 party 40 wasted 299    60291
Name: votes, dtype: int64
dist 11 party X wasted 44321
dist 11 party Z wasted 300    42668
Name: votes, dtype: int64
dist 12 party 98 wasted 304    21892
Name: votes, dtype: int64
dist 12 party X wasted 29053
dist 12 party Y wasted 303    83544
Name: votes, dtype: int64
dist 13 party 4 wasted 307    30807
Name: votes, dtype: int64
dist 13 party 40 wasted 306    67070
Name: votes, dtype: int64
dist 13 party X wasted 53674
dist 14 party 98 wasted 311    4282
Name: votes, dtype: int64
dist 14 party 99 wasted 312    3607
Name: votes, dtype: int64
dist 14 party X wasted 40902
dist 14 party Y wasted 310    46600
Name: votes, dtype: int64
dist 14 party Z wasted 309    63235
Name: votes, dtype: int64
dist 15 party 99 wasted 316    15667
Name: votes, dtype: int64
dist 15 party X wasted 30830
dist 15 party Y wasted 315    34943
Name: votes, dtype: int64
dist 15 party Z wasted 314    70325
Name: votes, dtype: int64
dist 16 party X wasted 13052
dist 16 party Y wasted 318    71405
Name: votes, dtype: int64
dist 16 party Z wasted 319    50568
Name: votes, dtype: int64
dist 17 party X wasted 78147
dist 17 party Y wasted 322    43138
Name: votes, dtype: int64
dist 17 party Z wasted 321    49485
Name: votes, dtype: int64
dist 18 party X wasted 324    95667
Name: votes, dtype: int64
dist 18 party Y wasted 1046
dist 18 party Z wasted 325    45081
Name: votes, dtype: int64
dist 19 party 4 wasted 329    17377
Name: votes, dtype: int64
dist 19 party 40 wasted 327    90540
Name: votes, dtype: int64
dist 19 party X wasted 5689
dist 19 party Z wasted 328    29743
Name: votes, dtype: int64
dist 20 party X wasted 49945
dist 20 party Y wasted 331    57741
Name: votes, dtype: int64
dist 20 party Z wasted 332    50439
Name: votes, dtype: int64
dist 21 party 98 wasted 336    6655
Name: votes, dtype: int64
dist 21 party X wasted 334    88225
Name: votes, dtype: int64
dist 21 party Y wasted 335    38195
Name: votes, dtype: int64
dist 21 party Z wasted 4131
dist 22 party 4 wasted 340    22859
Name: votes, dtype: int64
dist 22 party 40 wasted 338    91073
Name: votes, dtype: int64
dist 22 party X wasted 19420
dist 22 party Z wasted 339    30236
Name: votes, dtype: int64
dist 23 party X wasted 34072
dist 23 party Y wasted 343    58929
Name: votes, dtype: int64
dist 23 party Z wasted 342    76450
Name: votes, dtype: int64
dist 24 party 4 wasted 347    24349
Name: votes, dtype: int64
dist 24 party 40 wasted 345    61441
Name: votes, dtype: int64
dist 24 party X wasted 60890
dist 24 party Z wasted 346    39892
Name: votes, dtype: int64
dist 25 party 4 wasted 351    21031
Name: votes, dtype: int64
dist 25 party 40 wasted 349    44884
Name: votes, dtype: int64
dist 25 party X wasted 67130
dist 25 party Z wasted 350    38286
Name: votes, dtype: int64

,1,3,4,5,39,40,41,98,99,100,101,102,103,104,X,Y,Z
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3806.0,1570.0,1307.0,NaN,NaN,NaN,93234.0,3021.0,40376.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21763.0,91230.0,41955.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13328.0,45088.0,94380.0
3,NaN,NaN,26037.0,NaN,NaN,53480.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61759.0,NaN,35352.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2132.0,99182.0,45737.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4307.0,NaN,NaN,NaN,NaN,NaN,NaN,98422.0,1978.0,42862.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3850.0,NaN,NaN,NaN,NaN,NaN,85305.0,31813.0,25531.0
7,NaN,NaN,22399.0,NaN,NaN,76283.0,NaN,2931.0,11997.0,NaN,NaN,NaN,NaN,NaN,23580.0,NaN,41175.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4243.0,NaN,NaN,NaN,NaN,NaN,57548.0,57439.0,64731.0
9,NaN,NaN,20828.0,NaN,NaN,70168.0,NaN,1744.0,2107.0,NaN,NaN,NaN,NaN,NaN,20978.0,NaN,57901.0
10,NaN,NaN,25426.0,NaN,NaN,60291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44321.0,NaN,42668.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21892.0,NaN,NaN,NaN,NaN,NaN,NaN,29053.0,83544.0,NaN
12,NaN,NaN,30807.0,NaN,NaN,67070.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53674.0,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4282.0,3607.0,NaN,NaN,NaN,NaN,NaN,40902.0,46600.0,63235.0
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15667.0,NaN,NaN,NaN,NaN,NaN,30830.0,34943.0,70325.0
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13052.0,71405.0,50568.0
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78147.0,43138.0,49485.0
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95667.0,1046.0,45081.0
18,NaN,NaN,17377.0,NaN,NaN,90540.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5689.0,NaN,29743.0
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49945.0,57741.0,50439.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6655.0,NaN,NaN,NaN,NaN,NaN,NaN,88225.0,38195.0,4131.0
21,NaN,NaN,22859.0,NaN,NaN,91073.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19420.0,NaN,30236.0
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34072.0,58929.0,76450.0
23,NaN,NaN,24349.0,NaN,NaN,61441.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60890.0,NaN,39892.0
24,NaN,NaN,21031.0,NaN,NaN,44884.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67130.0,NaN,38286.0

# 何とか↑党派別できてない<- 要確認、できてるはず

同じ行に推薦が複数あるのはok
異なる行にいくつも推薦があるのはng

警告について
> prefが変更されている痕跡はない

In [67]:
totalvotes = pref[pref["win"] == 2]
totalvotes = sum(totalvotes["tvotes"])
totalvotes

614914

In [68]:
void = void.dropna(how='all', axis=1)
void

       98       99        X        Y        Z
0  2585.0      NaN  54204.0   6252.0  34087.0
1     NaN      NaN  64193.0  27950.0      NaN
2  3031.0  28990.0  66527.0      NaN      NaN
3  4320.0  65579.0   6693.0      NaN      NaN

In [69]:
void = void.fillna(0)
void

       98       99        X        Y        Z
0  2585.0      0.0  54204.0   6252.0  34087.0
1     0.0      0.0  64193.0  27950.0      0.0
2  3031.0  28990.0  66527.0      0.0      0.0
3  4320.0  65579.0   6693.0      0.0      0.0

In [70]:
#ラベルの有無で分けられないか?
void_copy = void.copy()[void.copy() > 0]
"""zimin = void_copy.loc[:,"X"]>0
yatou1 = void_copy.loc[:,"Y"]>0
yatou2 = void_copy.loc[:,"Z"]>0

try:
    yatou2 = void_copy.loc[:,"Z"]>0
    
except KeyError:
    print("自公",zimin.sum(),"立憲系",yatou1.sum())"""
#void_copy.loc[:,void_copy.columns.isin(["Z"])]はエラーの起きない取り方だが。。
all_party = void_copy.loc[:,void_copy.columns.isin(["X","Y","Z"])]
if len(all_party.columns) < 3:
    zimin = void_copy.loc[:,void_copy.columns.isin(["X"])]
    yatou1 = void_copy.loc[:,void_copy.columns.isin(["Y"])]
    
    zimin = zimin.dropna()
    yatou1 = yatou1.dropna()
    yatou2 = 0
    print (len(zimin),len(yatou1),yatou2)
    
else:
    zimin = void_copy.loc[:,void_copy.columns.isin(["X"])] 
    yatou1 = void_copy.loc[:,void_copy.columns.isin(["Y"])] 
    yatou2 = void_copy.loc[:,void_copy.columns.isin(["Z"])] 
    
    zimin = zimin.dropna()
    yatou1 = yatou1.dropna()
    yatou2 = yatou2.dropna()
    print (len(zimin),len(yatou1),len(yatou2))

4 2 1

In [71]:
nwv = void.sum()
nwv

98      9936.0
99     94569.0
X     191617.0
Y      34202.0
Z      34087.0
dtype: float64

In [72]:
nwv = void.sum()
nwv

98      9936.0
99     94569.0
X     191617.0
Y      34202.0
Z      34087.0
dtype: float64

In [73]:
dict_party = {"1":"自民党","3":"公明党","4":"共産党","5":"社民党","39":"希望の党","40":"立憲民主党","41":"日本維新の会","98":"その他","99":"その他・無所属",
              "100":"その他・無所属","101":"その他・無所属","X":"自公連立","Y":"野党共闘(立共社自)","Z":"野党共闘(希維)"}

In [74]:
#各党の総死票数の計算
nwv = void.sum()
nwv

kong = np.random.rand(len(void.columns),len(void.columns))
kong = pd.DataFrame(kong)
kong.columns = void.columns
kong.index = void.columns
kong = kong[kong[:] ==0]
#print(kong)

j = 1
k = 1
while j < len(nwv):   
    #print("------------")
    efgp_ep = []
    while k <= len(nwv): 
        #kong.append([j-1,"-",k])
        #print(kong)
        #print(j-1,"-",k)
        
        dif = nwv[j-1] - nwv[k]
        efgp_ep.append(dif)
        
        kong.iat[j-1,k] = dif/totalvotes*100
        
        k +=1    
        
        if k==len(nwv):
            break
    efgp = list(map(lambda x: x / totalvotes *100, efgp_ep))
    #print (efgp)
    
    k = j
    j += 1
kong

    98         99          X          Y          Z
98 NaN -13.763388 -29.545758  -3.946243  -3.927541
99 NaN   0.000000 -15.782370   9.817145   9.835847
X  NaN        NaN   0.000000  25.599515  25.618217
Y  NaN        NaN        NaN   0.000000   0.018702
Z  NaN        NaN        NaN        NaN        NaN

In [75]:
kong = kong.rename(columns = dict_party,index = dict_party)
kong

            その他    その他・無所属       自公連立  野党共闘(立共社自)   野党共闘(希維)
その他         NaN -13.763388 -29.545758   -3.946243  -3.927541
その他・無所属     NaN   0.000000 -15.782370    9.817145   9.835847
自公連立        NaN        NaN   0.000000   25.599515  25.618217
野党共闘(立共社自)  NaN        NaN        NaN    0.000000   0.018702
野党共闘(希維)    NaN        NaN        NaN         NaN        NaN

In [76]:
kong["その他"][1] = 0
kong

            その他    その他・無所属       自公連立  野党共闘(立共社自)   野党共闘(希維)
その他         NaN -13.763388 -29.545758   -3.946243  -3.927541
その他・無所属     0.0   0.000000 -15.782370    9.817145   9.835847
自公連立        NaN        NaN   0.000000   25.599515  25.618217
野党共闘(立共社自)  NaN        NaN        NaN    0.000000   0.018702
野党共闘(希維)    NaN        NaN        NaN         NaN        NaN

In [54]:
ef_all_party = kong.loc["自公連立":"野党共闘(希維)",kong.columns.isin(["自公連立","野党共闘(立共社自)","野党共闘(希維)"])]
#ef_zimin = kong.loc[:,kong.columns.isin(["野党共闘(希維)"])]
ef_all_party
if len(ef_all_party) < 3:
    ef_zimin_yatou1 = ef_all_party.iat[0,1]
    ef_zimin_yatou2 = 0
    ef_yatou1_yatou2 = 0
    
else:
    ef_zimin_yatou1 = ef_all_party.iat[0,1]
    ef_zimin_yatou2 = ef_all_party.iat[0,2]
    ef_yatou1_yatou2 = ef_all_party.iat[1,2]
    print(ef_zimin_yatou1,ef_zimin_yatou2,ef_yatou1_yatou2)

7.245243457167691 1.8554808380788772 -5.389762619088814

In [23]:
"""#から！
void = np.random.rand(3,4)

distnums = pref["distnum"][-1:]

void = np.random.rand(int(distnums),17)
void = pd.DataFrame(void)
void.columns = ["1","3","4","5","39","40","41","98","99","100","101","102","103","104","X","Y","Z"]
void = void[void[:] ==0]

distnum = 1

while distnum <= int(distnums):
    dist = pref[pref["distnum"] == distnum]
        #選挙区別に分けた<-distはdataframe

    if any(dist["rec1"] == 1) == 1 or any(dist["rec3"] == 1) == 1:
        dist.loc[dist["rec1"] == 1,"party"] = "X"
        dist.loc[dist["rec3"] == 1,"party"] = "X"
        
    if any(dist["rec4"] == 1) == 1 or any(dist["rec5"] == 1) or any(dist["rec40"] == 1) or any(dist["rec42"] == 1):
        oplist1rec = ["rec4","rec5","rec40","rec42"]
        for op1list in oplist1rec:
            dist.loc[dist[op1list] == 1, "party"] = "Y"
        #dist.loc[dist["rec4"] == 1,"party"] == "Y"
            
    elif any(dist["rec39"] == 1) == 1 or any(dist["rec41"] == 1) == 1:
        dist.loc[dist["rec39"] == 1,"party"] == "Z"
        dist.loc[dist["rec41"] == 1,"party"] == "Z"
        
    print(dist)
    
    for party in [1,3,4,5,39,40,41,98,99,"X","Y","Z"]:
        dist_each_party = dist[dist["party"] == party]
        
        #row=0でpass
        if len(dist_each_party) ==0:
            pass
        elif len(dist_each_party) >1:
            #print(dist_each_party)
            mul_ca=1
            #print("!!!!!",len(dist_each_party))
            while mul_ca <= len(dist_each_party):
                ex99 = dist_each_party[mul_ca-1:mul_ca]
                #print (ex99)
                if all(ex99["win"] == 2) == 1:
                    wasted = dist["votes"].iat[0] - dist["votes"].iat[1]
                    void[str(mul_ca-1 + party)][distnum-1] = wasted
                    
                elif all(ex99["win"] == 2) ==0:
                    wasted=ex99["votes"]
                    void[str(mul_ca + party)][distnum-1]=wasted
                print("dist",distnum,"party仮",mul_ca + party,"wasted",wasted)
                
                mul_ca +=1
                #print ("!!!!!",mul_ca)
                #if mul_ca==len(dist_each_party):
                    #break
                #else:
                    #pass
        
        else:

            if all(dist_each_party["win"] == 2) == 1:
                wasted = dist["votes"].iat[0] - dist["votes"].iat[1]

                void[str(party)][distnum-1] = wasted
            
            elif all(dist_each_party["win"] != 2) == 1:
                wasted=dist_each_party["votes"]
                
      
                void[str(party)][distnum-1] =wasted
                
            else:
                pass
                #wasted = dist["votes"]
            print("dist",distnum,"party",party,"wasted",wasted)
        
    distnum += 1
    #print(dist)
void"""

'#から！\nvoid = np.random.rand(3,4)\n\ndistnums = pref["distnum"][-1:]\n\nvoid = np.random.rand(int(distnums),17)\nvoid = pd.DataFrame(void)\nvoid.columns = ["1","3","4","5","39","40","41","98","99","100","101","102","103","104","X","Y","Z"]\nvoid = void[void[:] ==0]\n\ndistnum = 1\n\nwhile distnum <= int(distnums):\n    dist = pref[pref["distnum"] == distnum]\n        #選挙区別に分けた<-distはdataframe\n\n    if any(dist["rec1"] == 1) == 1 or any(dist["rec3"] == 1) == 1:\n        dist.loc[dist["rec1"] == 1,"party"] = "X"\n        dist.loc[dist["rec3"] == 1,"party"] = "X"\n        \n    if any(dist["rec4"] == 1) == 1 or any(dist["rec5"] == 1) or any(dist["rec40"] == 1) or any(dist["rec42"] == 1):\n        oplist1rec = ["rec4","rec5","rec40","rec42"]\n        for op1list in oplist1rec:\n            dist.loc[dist[op1list] == 1, "party"] = "Y"\n        #dist.loc[dist["rec4"] == 1,"party"] == "Y"\n            \n    elif any(dist["rec39"] == 1) == 1 or any(dist["rec41"] == 1) == 1:\n        dist.loc[dist["rec39"] == 1,"party"] == "Z"\n        dist.loc[dist["rec41"] == 1,"party"] == "Z"\n        \n    print(dist)\n    \n    for party in [1,3,4,5,39,40,41,98,99,"X","Y","Z"]:\n        dist_each_party = dist[dist["party"] == party]\n        \n        #row=0でpass\n        if len(dist_each_party) ==0:\n            pass\n        elif len(dist_each_party) >1:\n            #print(dist_each_party)\n            mul_ca=1\n            #print("!!!!!",len(dist_each_party))\n            while mul_ca <= len(dist_each_party):\n                ex99 = dist_each_party[mul_ca-1:mul_ca]\n                #print (ex99)\n                if all(ex99["win"] == 2) == 1:\n                    wasted = dist["votes"].iat[0] - dist["votes"].iat[1]\n                    void[str(mul_ca-1 + party)][distnum-1] = wasted\n                    \n                elif all(ex99["win"] == 2) ==0:\n                    wasted=ex99["votes"]\n                    void[str(mul_ca + party)][distnum-1]=wasted\n                print("dist",distnum,"party仮",mul_ca + party,"wasted",wasted)\n                \n                mul_ca +=1\n                #print ("!!!!!",mul_ca)\n                #if mul_ca==len(dist_each_party):\n                    #break\n                #else:\n                    #pass\n        \n        else:\n\n            if all(dist_each_party["win"] == 2) == 1:\n                wasted = dist["votes"].iat[0] - dist["votes"].iat[1]\n\n                void[str(party)][distnum-1] = wasted\n            \n            elif all(dist_each_party["win"] != 2) == 1:\n                wasted=dist_each_party["votes"]\n                \n      \n                void[str(party)][distnum-1] =wasted\n                \n            else:\n                pass\n                #wasted = dist["votes"]\n            print("dist",distnum,"party",party,"wasted",wasted)\n        \n    distnum += 1\n    #print(dist)\nvoid'

In [24]:
dfjj = df[df["party"] == 99]
dfj_j = dfjj[dfjj["win"] == 2]
dfjij = dfj_j[dfj_j["rec1"] != 1]
dfjkj = dfjij[dfjij["rec3"] != 1]
dfjlj = dfjkj[dfjkj["rec5"] != 1]
dfjlj

,id,name,prefid,pref,distnum,party,dual,win,inc,votes,...,last_kana,first_kana,rec1,rec3,rec4,rec5,rec39,rec40,rec41,rec42
18,19,逢坂誠二,1,Hokkaido,8,99,0,2,1,125771,...,おおさか,せいじ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,小沢一郎,3,Iwate,3,99,0,2,1,130229,...,おざわ,いちろう,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,62,安住淳,4,Miyagi,5,99,0,2,1,89423,...,あずみ,じゅん,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,85,金子恵美,7,Fukushima,1,99,0,2,1,126664,...,かねこ,えみ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,91,玄葉光一郎,7,Fukushima,3,99,0,2,1,92930,...,げんば,こういちろう,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,191,小泉龍司,11,Saitama,11,99,0,2,1,88290,...,こいずみ,りゅうじ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,221,野田佳彦,12,Chiba,4,99,0,2,1,131024,...,のだ,よしひこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,378,江田憲司,14,Kanagawa,8,99,0,2,1,119280,...,えだ,けんじ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,415,鷲尾英一郎,15,Niigata,2,99,0,2,1,97808,...,わしお,えいいちろう,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,452,中島克仁,19,Yamanashi,1,99,0,2,1,107007,...,なかじま,かつひと,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,539,山尾志桜里,23,Aichi,7,99,0,2,1,128163,...,やまお,しおり,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,554,重徳和彦,23,Aichi,12,99,0,2,1,103088,...,しげとく,かずひこ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,568,中川正春,24,Mie,2,99,0,2,1,122518,...,なかがわ,まさはる,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
569,570,岡田克也,24,Mie,3,99,0,2,1,147255,...,おかだ,かつや,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,593,前原誠司,26,Kyoto,2,99,0,2,1,65480,...,まえはら,せいじ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,646,平野博文,27,Osaka,11,99,0,2,1,76144,...,ひらの,ひろふみ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
830,831,広田一,39,Kochi,2,99,0,2,0,92179,...,ひろた,はじめ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
865,866,原口一博,41,Saga,1,99,0,2,1,105487,...,はらぐち,かずひろ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
930,931,玉城デニー,47,Okinawa,3,99,0,2,1,95517,...,たまき,でにー,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## めんどくさいのでxlsxに書き出します
[参考](https://note.nkmk.me/python-pandas-to-excel/)

In [25]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (2.5.8)
Requirement already satisfied: et-xmlfile in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from openpyxl) (1.0.1)
Requirement already satisfied: jdcal in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from openpyxl) (1.4)
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [26]:
import openpyxl

In [27]:
kong.to_excel("/home/nbuser/library/oridinal2.xlsx",sheet_name = "sonomama")

### ~~どうすれば機械的にエクセルにぶち込めるのか~~
そもそもpandas上で処理すればいい
1. 空のデータフレームを作っておいて、そこに行列をずらしながら代入
> そもそも3勢力が揃わない地区がある
>> ifで分岐させる 

~~~python
#table_japanは繰り返しの前に作成しておく、そして外に置く
table_japan = np.random.rand(47,7)
table_japan = pd.DataFrame(table_japan)
#7*47のdataframeを生成
table_japan = table_japan[table_japan[:] == 0]
#中身を0に入れ替える
table_japan.columns = ["都道府県","自公候補者数","野党共闘1候補者数","野党共闘2候補者数","自公-野党1ギャップ","自公-野党2ギャップ","野党1-野党2ギャップ"]
#都道府県名をrowのラベルにするべきでは？
#kongにはすでに都道府県名のデータはない->prefにある、voidでは各勢力の立候補者数がわかる
pref_name = pref.iat[0,3] 
table_japan.iat[prefid - 1,0] = pref_name
#prefidを使う?
#これをprefの後に入れておく
table_japan.iat[prefid - 1,1] = zimin
table_japan.iat[prefid - 1,2] = yatou1
table_japan.iat[prefid - 1,3] = yatou2

#kongからefigapを取り出す
table_japan.iat[prefid - 1,4] = ef_zimin_yatou1
table_japan.iat[prefid - 1,5] = ef_zimin_yatou2
table_japan.iat[prefid - 1,6] = ef_yatou2_yatou2
~~~

↑~~廃棄~~ しません　転用します
pandasでもbokehでも描画はできる
> なお、一度dataframeに結果を入れる必要がある

~~~python

[ラベルの存在の有無で抽出](http://sinhrks.hatenablog.com/entry/2014/11/15/230705)

In [28]:
!pip install bokeh

Requirement already satisfied: bokeh in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (0.13.0)
Requirement already satisfied: six>=1.5.2 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from bokeh) (1.11.0)
Requirement already satisfied: PyYAML>=3.10 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from bokeh) (3.13)
Requirement already satisfied: python-dateutil>=2.1 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from bokeh) (2.8.0)
Requirement already satisfied: Jinja2>=2.7 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from bokeh) (2.10)
Requirement already satisfied: numpy>=1.7.1 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from bokeh) (1.16.2)
Requirement already satisfied: packaging>=16.8 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from bokeh) (18.0)
Requirement already satisfied: tornado>=4.3 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from bokeh) (4.5.3)
Requirement already satisfied: MarkupSafe>=0.23 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from Jinja2>=2.7->bokeh) (1.1.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (from packaging>=16.8->bokeh) (2.3.0)
WARNING: You are using pip version 19.2.2, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [29]:
import bokeh

# その他政党と無所属の処理がある
県内1選挙区でしか立候補していないその他政党・無所属に関しては党派性に基づいたゲリマンダーに関係していない(とも言い切れない?)
> というかefficiency gapが計算できない
>> 異常に大きな値になる

> ~~データを読む際に無視すればよくね？~~


↓一選挙区にしか出ていない無所属、その他を消した場合

In [30]:
void

,4,40,98,99,100,101,X,Y,Z
0,0.0,0.0,0.0,3806.0,1570.0,1307.0,93234.0,3021.0,40376.0
1,0.0,0.0,0.0,0.0,0.0,0.0,21763.0,91230.0,41955.0
2,0.0,0.0,0.0,0.0,0.0,0.0,13328.0,45088.0,94380.0
3,26037.0,53480.0,0.0,0.0,0.0,0.0,61759.0,0.0,35352.0
4,0.0,0.0,0.0,0.0,0.0,0.0,2132.0,99182.0,45737.0
5,0.0,0.0,4307.0,0.0,0.0,0.0,98422.0,1978.0,42862.0
6,0.0,0.0,0.0,3850.0,0.0,0.0,85305.0,31813.0,25531.0
7,22399.0,76283.0,2931.0,11997.0,0.0,0.0,23580.0,0.0,41175.0
8,0.0,0.0,0.0,4243.0,0.0,0.0,57548.0,57439.0,64731.0
9,20828.0,70168.0,1744.0,2107.0,0.0,0.0,20978.0,0.0,57901.0
10,25426.0,60291.0,0.0,0.0,0.0,0.0,44321.0,0.0,42668.0
11,0.0,0.0,21892.0,0.0,0.0,0.0,29053.0,83544.0,0.0
12,30807.0,67070.0,0.0,0.0,0.0,0.0,53674.0,0.0,0.0
13,0.0,0.0,4282.0,3607.0,0.0,0.0,40902.0,46600.0,63235.0
14,0.0,0.0,0.0,15667.0,0.0,0.0,30830.0,34943.0,70325.0
15,0.0,0.0,0.0,0.0,0.0,0.0,13052.0,71405.0,50568.0
16,0.0,0.0,0.0,0.0,0.0,0.0,78147.0,43138.0,49485.0
17,0.0,0.0,0.0,0.0,0.0,0.0,95667.0,1046.0,45081.0
18,17377.0,90540.0,0.0,0.0,0.0,0.0,5689.0,0.0,29743.0
19,0.0,0.0,0.0,0.0,0.0,0.0,49945.0,57741.0,50439.0
20,0.0,0.0,6655.0,0.0,0.0,0.0,88225.0,38195.0,4131.0
21,22859.0,91073.0,0.0,0.0,0.0,0.0,19420.0,0.0,30236.0
22,0.0,0.0,0.0,0.0,0.0,0.0,34072.0,58929.0,76450.0
23,24349.0,61441.0,0.0,0.0,0.0,0.0,60890.0,0.0,39892.0
24,21031.0,44884.0,0.0,0.0,0.0,0.0,67130.0,0.0,38286.0

In [31]:
none_list = []
none_list = void.columns
print(none_list)

if ("98" in none_list) or ("99" in none_list) or ("100" in none_list):
    pass

else:
    pass

Index(['4', '40', '98', '99', '100', '101', 'X', 'Y', 'Z'], dtype='object')

In [32]:
totalvotes = pref[pref["win"] == 2]
totalvotes = sum(totalvotes["tvotes"])
totalvotes

5848996

In [33]:
def get_pref(prefid):
    get_pref = df[df["prefid"] == prefid] 
    return get_pref

In [ ]:
prefid = 2

#prefidから各都道府県のデータに分ける
pref = df[df["prefid"] == prefid]

    #結果を出力するための空のデータフレームを作る
void = np.random.rand(3,4)
    
    #データフレームの大きさの調整
distnums = pref["distnum"][-1:]
    
void = np.random.rand(int(distnums),17)
    #void = np.random.rand(int(distnums),len(cols))
void = pd.DataFrame(void)
void.columns = ["1","3","4","5","39","40","41","98","99","100","101","102","103","104","X","Y","Z"]
void = void[void[:] ==0]

    #繰り返しにより党派別に分け死票を計算
distnum = 1
    
while distnum <= int(distnums):
    dist = pref[pref["distnum"] == distnum]
        #選挙区別に分けた
        
    if any(dist["party"] == 1) == 1 or any(dist["party"] == 1) == 1:
        dist.loc[dist["party"] == 1,"party"] = "X"
        dist.loc[dist["party"] == 3,"party"] = "X"
    
    if any(dist["party"] == 4) == 1 or any(dist["party"] == 5) or any(dist["party"] == 40) == 1:
        oplist1=[4,5,40]
        opposition_party1 = dist[(dist["party"] == 4) | (dist["party"] == 5) | (dist["party"] == 40)]
            #print(opposition_party1)
        
        if len(opposition_party1) > 1:
            pass
        
        else:
            for op1 in oplist1:
                dist.loc[dist["party"] == op1, "party"] = "Y"
        
    if any(dist["party"] == 39) == 1 or any(dist["party"] == 41) == 1:
        oplist2=[39,41]
        opposition_party2 = dist[(dist["party"] == 39) | (dist["party"] == 41)]
            #print(opposition_party2)
        
        if len(opposition_party2) > 1:
            pass
        
        else:
            for op2 in oplist2:
                dist.loc[dist["party"] == op2, "party"] = "Z"
        
                #print(dist)
            
    if any(dist["rec1"] == 1) == 1 or any(dist["rec3"] == 1) == 1:
        dist.loc[dist["rec1"] == 1,"party"] = "X"
        dist.loc[dist["rec3"] == 1,"party"] = "X"
        
    if any(dist["rec4"] == 1) == 1 or any(dist["rec5"] == 1) or any(dist["rec40"] == 1) or any(dist["rec42"] == 1):
        oplist1rec = ["rec4","rec5","rec40","rec42"]
        for op1list in oplist1rec:
            dist.loc[dist["party"] == op1list, "party"] = "Y"
            
    if any(dist["rec39"] == 1) == 1 or any(dist["rec41"] == 1) == 1:
        dist.loc[dist["rec39"] == 1,"party"] == "Z"
        dist.loc[dist["rec41"] == 1,"party"] == "Z"
        
            #print(dist)
    
        for party in [1,3,4,5,39,40,41,98,99,"X","Y","Z"]:
            dist_each_party = dist[dist["party"] == party]
        
            #row=0でpass
            if len(dist_each_party) ==0:
                pass
            elif len(dist_each_party) >1:
                #print(dist_each_party)
                mul_ca=1
                #print("!!!!!",len(dist_each_party))
                while mul_ca <= len(dist_each_party):
                    ex99 = dist_each_party[mul_ca-1:mul_ca]
                    #print (ex99)
                    if all(ex99["win"] == 2) == 1:
                        wasted = dist["votes"].iat[0] - dist["votes"].iat[1]
                        void[str(mul_ca-1 + party)][distnum-1] = wasted
                    
                    elif all(ex99["win"] == 2) ==0:
                        wasted=ex99["votes"]
                        void[str(mul_ca + party)][distnum-1]=wasted
                        #print("dist",distnum,"party仮",mul_ca + party,"wasted",wasted)
                
                    mul_ca +=1
        
            else:

                if all(dist_each_party["win"] == 2) == 1:
                    wasted = dist["votes"].iat[0] - dist["votes"].iat[1]

                    void[str(party)][distnum-1] = wasted
            
                elif all(dist_each_party["win"] != 2) == 1:
                    wasted=dist_each_party["votes"]
      
                    void[str(party)][distnum-1] = wasted
                
                else:
                    pass
                #wasted = dist["votes"]
                        #print("dist",distnum,"party",party,"wasted",wasted)
        
        distnum += 1
        #print(dist)
void
    
totalvotes = pref[pref["win"] == 2]
totalvotes = sum(totalvotes["tvotes"])
    
void = void.dropna(how='all', axis=1)
    
void = void.fillna(0)
    
nwv = void.sum()
    
    #各党の総死票数の計算
nwv = void.sum()
    
dict_party = {"1":"自民党","3":"公明党","4":"共産党","5":"社民党","39":"希望の党","40":"立憲民主党","41":"日本維新の会","98":"その他","99":"その他・無所属",
              "100":"その他・無所属","101":"その他・無所属","X":"自公連立","Y":"野党共闘(立共社自)","Z":"野党共闘(希維)"}
    
kong = np.random.rand(len(void.columns),len(void.columns))
kong = pd.DataFrame(kong)
kong.columns = void.columns
kong.index = void.columns
kong = kong[kong[:] ==0]

j = 1
k = 1
while j < len(nwv):   
        #print("------------")
    efgp_ep = []
    while k <= len(nwv): 

        dif = nwv[j-1] - nwv[k]
        efgp_ep.append(dif)
        
        kong.iat[j-1,k] = dif/totalvotes*100
        
        k +=1    
        
        if k==len(nwv):
            break
    efgp = list(map(lambda x: x / totalvotes *100, efgp_ep))
    #print (efgp)
    
    k = j
    j += 1
kong
    
    #kong = kong.rename(columns = dict_party,index = dict_party)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s